#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=aggregate-topics
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=01:00:00
#SBATCH --output=$HOME/output/success/aggregate-%x.%A.out
#SBATCH --error=$HOME/output/error/aggregate-%x.%A.err

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/LLM4CS/
source activate pyserini

PROMPTING_METHOD="RAR" # Choose prompting method= REW, RAR, RTR (FOR NOW ONLY TESTING WITH REW)
AGGREGATION_METHOD="mean"  # Choose aggregation method: maxprob, mean


# Paths
 INPUT="results/new/cast19/${PROMPTING_METHOD}/rewrites.jsonl"  # Input file with REW


OUTPUT="results/new/cast19/${PROMPTING_METHOD}/topics_${AGGREGATION_METHOD}_${PROMPTING_METHOD}_sparse.msmarco-passage.dev-subset.tsv"
# HAS TO BE A TSV FILE IN ORDER TO WORK

PYTHON="aggregate_topics_sparse_${PROMPTING_METHOD}.py"
# Step 1: Aggregate topics
echo "Aggregating topics using ${AGGREGATION_METHOD} method..."
python  $PYTHON \
  --input $INPUT \
  --output $OUTPUT \
  --aggregation-method $AGGREGATION_METHOD \
   

echo "Aggregation completed!"
echo "output file:${OUTPUT}"
