#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=output/success/out-%x.%A.out
#SBATCH --error=output/error/out-%x.%A.err

module purge
module load 2022
module load Anaconda3/2022.05

# Go to the directory that contains the conda env file and install it
cd $HOME/LLM4CS/
# conda env create -f environment.yaml
conda create -n llmcs python=3.8 numpy=1.22.3 -y

source activate llmcs

# Step 3: Install PyTorch with CUDA support separately
conda install pytorch==1.12.0 cudatoolkit=11.3 -c pytorch -y

conda install -c conda-forge mkl-fft mkl-random

# Step 4: Install the remaining requirements
pip install -r requirements.txt
